Update Dockerfile

diff --git a/all-in-one/Dockerfile b/all-in-one/Dockerfile
--- a/all-in-one/Dockerfile
+++ b/all-in-one/Dockerfile
@@ -1,170 +1,104 @@
-FROM phusion/baseimage:0.11
-MAINTAINER Sebastien Pujadas http://pujadas.net
-ENV \
- REFRESHED_AT=2017-02-28
+################################################################################
+# This Dockerfile was generated from the template at distribution/src/docker/Dockerfile
+#
+# Beginning of multi stage Dockerfile
+################################################################################
 
+################################################################################
+# Build stage 0 `builder`:
+# Extract elasticsearch artifact
+# Install required plugins
+# Set gid=0 and make group perms==owner perms
+################################################################################
 
-###############################################################################
-#                                INSTALLATION
-###############################################################################
+FROM centos:7 AS builder
 
-### install prerequisites (cURL, gosu, JDK, tzdata)
+RUN for iter in {1..10}; do yum update --setopt=tsflags=nodocs -y && \
+    yum install --setopt=tsflags=nodocs -y gzip shadow-utils tar && \
+    yum clean all && exit_code=0 && break || exit_code=\$? && echo "yum error: retry \$iter in 10s" && sleep 10; done; \
+    (exit \$exit_code)
 
-RUN set -x \
- && apt update -qq \
- && apt install -qqy --no-install-recommends ca-certificates curl gosu tzdata openjdk-8-jdk \
- && apt clean \
- && rm -rf /var/lib/apt/lists/* \
- && gosu nobody true \
- && set +x
+ENV PATH /usr/share/elasticsearch/bin:\$PATH
 
-### install Elasticsearch
-ARG ELK_VERSION=7.4.0
-ENV \
- ES_VERSION=${ELK_VERSION} \
- ES_HOME=/opt/elasticsearch \
- LOGSTASH_VERSION=${ELK_VERSION} \
- LOGSTASH_HOME=/opt/logstash
+RUN groupadd -g 1000 elasticsearch && \
+    adduser -u 1000 -g 1000 -d /usr/share/elasticsearch elasticsearch
 
-# note you can't define an env var that references another one in the same block (docker layer)
-ENV \
- JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre \
- ES_PACKAGE=elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz \
- ES_GID=991 \
- ES_UID=991 \
- ES_PATH_CONF=/etc/elasticsearch \
- ES_PATH_BACKUP=/var/backups \
- KIBANA_VERSION=${ELK_VERSION}
+WORKDIR /usr/share/elasticsearch
 
-RUN echo "${ELK_VERSION} ${ES_VERSION} https://artifacts.elastic.co/downloads/elasticsearch/${ES_PACKAGE} to ${ES_HOME}"
-RUN DEBIAN_FRONTEND=noninteractive \
- && mkdir ${ES_HOME} \
- && curl -O https://artifacts.elastic.co/downloads/elasticsearch/${ES_PACKAGE} \
- && tar xzf ${ES_PACKAGE} -C ${ES_HOME} --strip-components=1 \
- && rm -f ${ES_PACKAGE} \
- && groupadd -r elasticsearch -g ${ES_GID} \
- && useradd -r -s /usr/sbin/nologin -M -c "Elasticsearch service user" -u ${ES_UID} -g elasticsearch elasticsearch \
- && mkdir -p /var/log/elasticsearch ${ES_PATH_CONF} ${ES_PATH_CONF}/scripts /var/lib/elasticsearch ${ES_PATH_BACKUP} \
- && chown -R elasticsearch:elasticsearch ${ES_HOME} /var/log/elasticsearch /var/lib/elasticsearch ${ES_PATH_CONF} ${ES_PATH_BACKUP}
+${source_elasticsearch}
 
+RUN tar zxf /opt/${elasticsearch} --strip-components=1
+RUN grep ES_DISTRIBUTION_TYPE=tar /usr/share/elasticsearch/bin/elasticsearch-env \
+    && sed -i -e 's/ES_DISTRIBUTION_TYPE=tar/ES_DISTRIBUTION_TYPE=docker/' /usr/share/elasticsearch/bin/elasticsearch-env
+RUN mkdir -p config data logs
+RUN chmod 0775 config data logs
+COPY config/elasticsearch.yml config/log4j2.properties config/
+RUN chmod 0660 config/elasticsearch.yml config/log4j2.properties
 
-### install Logstash
+################################################################################
+# Build stage 1 (the actual elasticsearch image):
+# Copy elasticsearch from stage 0
+# Add entrypoint
+################################################################################
 
-ENV \
- LOGSTASH_PACKAGE=logstash-${LOGSTASH_VERSION}.tar.gz \
- LOGSTASH_GID=992 \
- LOGSTASH_UID=992 \
- LOGSTASH_PATH_CONF=/etc/logstash \
- LOGSTASH_PATH_SETTINGS=${LOGSTASH_HOME}/config
+FROM centos:7
 
-RUN mkdir ${LOGSTASH_HOME} \
- && curl -O https://artifacts.elastic.co/downloads/logstash/${LOGSTASH_PACKAGE} \
- && tar xzf ${LOGSTASH_PACKAGE} -C ${LOGSTASH_HOME} --strip-components=1 \
- && rm -f ${LOGSTASH_PACKAGE} \
- && groupadd -r logstash -g ${LOGSTASH_GID} \
- && useradd -r -s /usr/sbin/nologin -d ${LOGSTASH_HOME} -c "Logstash service user" -u ${LOGSTASH_UID} -g logstash logstash \
- && mkdir -p /var/log/logstash ${LOGSTASH_PATH_CONF}/conf.d \
- && chown -R logstash:logstash ${LOGSTASH_HOME} /var/log/logstash ${LOGSTASH_PATH_CONF}
+ENV ELASTIC_CONTAINER true
 
+RUN for iter in {1..10}; do yum update --setopt=tsflags=nodocs -y && \
+    yum install --setopt=tsflags=nodocs -y nc shadow-utils zip unzip && \
+    yum clean all && exit_code=0 && break || exit_code=\$? && echo "yum error: retry \$iter in 10s" && sleep 10; done; \
+    (exit \$exit_code)
 
-### install Kibana
+RUN groupadd -g 1000 elasticsearch && \
+    adduser -u 1000 -g 1000 -G 0 -d /usr/share/elasticsearch elasticsearch && \
+    chmod 0775 /usr/share/elasticsearch && \
+    chgrp 0 /usr/share/elasticsearch
 
-ENV \
- KIBANA_HOME=/opt/kibana \
- KIBANA_PACKAGE=kibana-${KIBANA_VERSION}-linux-x86_64.tar.gz \
- KIBANA_GID=993 \
- KIBANA_UID=993
+WORKDIR /usr/share/elasticsearch
+COPY --from=builder --chown=1000:0 /usr/share/elasticsearch /usr/share/elasticsearch
 
-RUN mkdir ${KIBANA_HOME} \
- && curl -O https://artifacts.elastic.co/downloads/kibana/${KIBANA_PACKAGE} \
- && tar xzf ${KIBANA_PACKAGE} -C ${KIBANA_HOME} --strip-components=1 \
- && rm -f ${KIBANA_PACKAGE} \
- && groupadd -r kibana -g ${KIBANA_GID} \
- && useradd -r -s /usr/sbin/nologin -d ${KIBANA_HOME} -c "Kibana service user" -u ${KIBANA_UID} -g kibana kibana \
- && mkdir -p /var/log/kibana \
- && chown -R kibana:kibana ${KIBANA_HOME} /var/log/kibana
+# Replace OpenJDK's built-in CA certificate keystore with the one from the OS
+# vendor. The latter is superior in several ways.
+# REF: https://github.com/elastic/elasticsearch-docker/issues/171
+RUN ln -sf /etc/pki/ca-trust/extracted/java/cacerts /usr/share/elasticsearch/jdk/lib/security/cacerts
 
+ENV PATH /usr/share/elasticsearch/bin:\$PATH
 
-###############################################################################
-#                              START-UP SCRIPTS
-###############################################################################
+COPY --chown=1000:0 bin/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
 
-### Elasticsearch
+# Openshift overrides USER and uses ones with randomly uid>1024 and gid=0
+# Allow ENTRYPOINT (and ES) to run even with a different user
+RUN chgrp 0 /usr/local/bin/docker-entrypoint.sh && \
+    chmod g=u /etc/passwd && \
+    chmod 0775 /usr/local/bin/docker-entrypoint.sh
 
-ADD ./elasticsearch-init /etc/init.d/elasticsearch
-RUN sed -i -e 's#^ES_HOME=$#ES_HOME='$ES_HOME'#' /etc/init.d/elasticsearch \
- && chmod +x /etc/init.d/elasticsearch
+EXPOSE 9200 9300
 
-### Logstash
+LABEL org.label-schema.build-date="${build_date}" \
+  org.label-schema.license="${license}" \
+  org.label-schema.name="Elasticsearch" \
+  org.label-schema.schema-version="1.0" \
+  org.label-schema.url="https://www.elastic.co/products/elasticsearch" \
+  org.label-schema.usage="https://www.elastic.co/guide/en/elasticsearch/reference/index.html" \
+  org.label-schema.vcs-ref="${git_revision}" \
+  org.label-schema.vcs-url="https://github.com/elastic/elasticsearch" \
+  org.label-schema.vendor="Elastic" \
+  org.label-schema.version="${version}" \
+  org.opencontainers.image.created="${build_date}" \
+  org.opencontainers.image.documentation="https://www.elastic.co/guide/en/elasticsearch/reference/index.html" \
+  org.opencontainers.image.licenses="${license}" \
+  org.opencontainers.image.revision="${git_revision}" \
+  org.opencontainers.image.source="https://github.com/elastic/elasticsearch" \
+  org.opencontainers.image.title="Elasticsearch" \
+  org.opencontainers.image.url="https://www.elastic.co/products/elasticsearch" \
+  org.opencontainers.image.vendor="Elastic" \
+  org.opencontainers.image.version="${version}"
 
-ADD ./logstash-init /etc/init.d/logstash
-RUN sed -i -e 's#^LS_HOME=$#LS_HOME='$LOGSTASH_HOME'#' /etc/init.d/logstash \
- && chmod +x /etc/init.d/logstash
+ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
+# Dummy overridable parameter parsed by entrypoint
+CMD ["eswrapper"]
 
-### Kibana
-
-ADD ./kibana-init /etc/init.d/kibana
-RUN sed -i -e 's#^KIBANA_HOME=$#KIBANA_HOME='$KIBANA_HOME'#' /etc/init.d/kibana \
- && chmod +x /etc/init.d/kibana
-
-
-###############################################################################
-#                               CONFIGURATION
-###############################################################################
-
-### configure Elasticsearch
-
-ADD ./elasticsearch.yml ${ES_PATH_CONF}/elasticsearch.yml
-ADD ./elasticsearch-default /etc/default/elasticsearch
-RUN cp ${ES_HOME}/config/log4j2.properties ${ES_HOME}/config/jvm.options \
-    ${ES_PATH_CONF} \
- && chown -R elasticsearch:elasticsearch ${ES_PATH_CONF} \
- && chmod -R +r ${ES_PATH_CONF}
-
-### configure Logstash
-
-# certs/keys for Beats and Lumberjack input
-RUN mkdir -p /etc/pki/tls/{certs,private}
-ADD ./logstash-beats.crt /etc/pki/tls/certs/logstash-beats.crt
-ADD ./logstash-beats.key /etc/pki/tls/private/logstash-beats.key
-
-# pipelines
-ADD pipelines.yml ${LOGSTASH_PATH_SETTINGS}/pipelines.yml
-
-# filters
-ADD ./logstash-conf/*.conf ${LOGSTASH_PATH_CONF}/conf.d/
-
-# patterns
-ADD ./nginx.pattern ${LOGSTASH_HOME}/patterns/nginx
-RUN chown -R logstash:logstash ${LOGSTASH_HOME}/patterns
-
-# Fix permissions
-RUN chmod -R +r ${LOGSTASH_PATH_CONF} ${LOGSTASH_PATH_SETTINGS} \
- && chown -R logstash:logstash ${LOGSTASH_PATH_SETTINGS}
-
-### configure logrotate
-
-ADD ./elasticsearch-logrotate /etc/logrotate.d/elasticsearch
-ADD ./logstash-logrotate /etc/logrotate.d/logstash
-ADD ./kibana-logrotate /etc/logrotate.d/kibana
-RUN chmod 644 /etc/logrotate.d/elasticsearch \
- && chmod 644 /etc/logrotate.d/logstash \
- && chmod 644 /etc/logrotate.d/kibana
-
-
-### configure Kibana
-
-ADD ./kibana.yml ${KIBANA_HOME}/config/kibana.yml
-
-
-###############################################################################
-#                                   START
-###############################################################################
-
-ADD ./start.sh /usr/local/bin/start.sh
-RUN chmod +x /usr/local/bin/start.sh
-
-EXPOSE 5601 9200 9300 5044
-VOLUME /var/lib/elasticsearch
-
-CMD [ "/usr/local/bin/start.sh" ]
+################################################################################
+# End of multi-stage Dockerfile
+################################################################################
